[package]
name = "falling_sand_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
profiling = "1.0.3"
rand = "0.8.4"
simdnoise = "3.1.6"
futures = { version = "0.3.15", features = [] }
tokio = {version = "1.8.1", features = ["rt", "rt-multi-thread", "macros"] }
lazy_static = "1.4.0"
imgui = "0.7.0"
imgui-sdl2 = "0.14.0"
imgui-opengl-renderer = "0.11.0"
sysinfo = "0.19.1" # should be optional in the future
liquidfun = { git = "https://github.com/PieKing1215/custom-liquidfun-rust" }
sdl_gpu = { git = "https://github.com/PieKing1215/sdl-gpu-rust" }

[features]
#default = ["profile-with-tracy"]
profile-with-tracy = ["profiling/profile-with-tracy"]

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["ttf","image","gfx","static-link","use-vcpkg"]

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-gfx", "sdl2-image[libjpeg-turbo,libwebp]", "sdl2-ttf"]
git = "https://github.com/microsoft/vcpkg"
branch = "master"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }

[profile.dev]
opt-level = 1