[package]
name = "fs_client"
version = "0.1.0"
authors = ["PieKing1215"]
description = "Falling Sand Engine client"
repository = "https://github.com/PieKing1215/FallingSandEngine"
readme = "README.md"
license = "ARR"
keywords = ["game", "falling-sand", "2d"]
categories = ["game-engines", "games"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_common = { path = "../fs_common" }
log = "0.4"
profiling = "1.0"
clap = { version = "3.0", features = ["cargo"] }
imgui = { git = "https://github.com/PieKing1215/imgui-rs.git", branch = "custom-edit" }
imgui-sdl2-support = { git = "https://github.com/PieKing1215/imgui-rs.git", branch = "custom-edit" }
imgui-glow-renderer = { git = "https://github.com/PieKing1215/imgui-rs.git", branch = "custom-edit" }
sdl2 = { version = "0.35", default-features = false, features = ["ttf","image","gfx","static-link","use-vcpkg"] }
sdl_gpu = { git = "https://github.com/PieKing1215/sdl-gpu-rust" }
glow = "0.10" # imgui-glow-renderer uses old version
specs = { version = "0.17", features = ["serde", "specs-derive"] }
salva2d = { version = "0.7", features = ["rapier"] }
rapier2d = { version = "0.11", features = ["simd-stable"] }
sysinfo = "0.23" # TODO: should be optional in the future
bincode = "1.3"

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-gfx", "sdl2-image[libjpeg-turbo,libwebp]", "sdl2-ttf"]
git = "https://github.com/microsoft/vcpkg"
branch = "master"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }
