[package]
name = "fs_common"
version = "0.1.0"
authors = ["PieKing1215"]
description = "Falling Sand Engine common"
repository = "https://github.com/PieKing1215/FallingSandEngine"
readme = "README.md"
license = "ARR"
keywords = ["game", "falling-sand", "2d"]
categories = ["game-engines", "games"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14"
profiling = "1.0"
rand = "0.8"
simdnoise = "3.1"
futures = { version = "0.3", features = [] }
lazy_static = "1.4"
imgui = { git = "https://github.com/PieKing1215/imgui-rs.git", branch = "custom-edit" }
imgui-sdl2-support = { git = "https://github.com/PieKing1215/imgui-rs.git", branch = "custom-edit" }
imgui-glow-renderer = { git = "https://github.com/PieKing1215/imgui-rs.git", branch = "custom-edit" }
glow = "0.10" # imgui-glow-renderer uses old version
sysinfo = "0.23" # TODO: should be optional in the future
sdl2 = { version = "0.35", default-features = false, features = ["ttf","image","gfx","static-link","use-vcpkg"] }
sdl_gpu = { git = "https://github.com/PieKing1215/sdl-gpu-rust" }
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.3"
bincode = "1.3"
toml = "0.5"
# serde_json = "1.0"
clap = { version = "3.0", features = ["cargo"] }
crossterm = "0.23"
log = "0.4"
simplelog = "0.11"
tui = { version = "0.17", default-features = false, features = ["crossterm"] }
tui-logger = "0.7"
backtrace = "0.3"
specs = { version = "0.17", features = ["serde", "specs-derive"] }
specs-derive = "0.4"
bitflags = "1.3"
fastrand = "1.6.0"
drain_filter_polyfill = "0.1"
retain_mut = "0.1"
salva2d = { version = "0.7", features = ["rapier"] }
rapier2d = { version = "0.11", features = ["simd-stable"] }
rayon = "1.5"
num_cpus = "1.13"
itertools = "0.10"
async-scoped = { version = "0.7", features = ["use-tokio"] }

# mesh generation
contour = "0.4"
geojson = "0.22"
ramer_douglas_peucker = "0.2"
mint = "0.5"
earcutr = "0.2"

[features]
#default = ["profile-with-tracy"]
profile = ["profiling/profile-with-tracy"]

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-gfx", "sdl2-image[libjpeg-turbo,libwebp]", "sdl2-ttf"]
git = "https://github.com/microsoft/vcpkg"
branch = "master"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }

[dev-dependencies]
criterion = "0.3"

# [[bench]]
# name = "benchmark"
# harness = false