name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Build and package
      run: sh package.sh
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: "fss-${{ steps.short-sha.outputs.sha }}"
        path: package/
